server:
  port: 19093
  
spring:  
  http:
    log-request-details: true  
      
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
  
eureka:
  client:
    enabled: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true
    healthcheck:
      enabled: true
  instance:
    instance-id: ${spring.application.name}:${random.int}
      
    
swagger: 
  config: 
    refreshrate: 6000
    
logging:
  file: /var/log/${spring.application.name}.log
  level:
    root: info 